### ISSUE TITLE
Readme empty.

### ISSUE THREAD

**Issue by sjoerd0301** [ddnetters/ddnetters#1]
The readme is empty, what is this repo for?
Are you really dominique?
What is the purpose of life, why are we even here?

**Comment by ddnetters** [comment]
Hi @sjoerd0301,

Thank you for contacting us. Contents of our README files can be unlocked using our special **CodeReviewPremium™** subscription package, for the low price of $99.99 / seat / 4 weeks.

I've upgraded your account with a free 42 minute trials, _after which your credit card will automatically be charged_. Please note that cancellations can only be performed by one of our **CodeReviewPremium™** operatives, reachable by phone every third Monday of the month between 2am and 4am CET.

Our NLP algorithm detected that you'd like to receive our newsletter as well. I've added your work and personal email to our twice-daily newsletter about other interesting newsletters.

This is an auto-generated email, no replies are possible. For any questions please contact one of our **CodeReviewPremium™** operatives.
